### ISSUE TITLE
[TODO] Qt6 transition 

### ISSUE THREAD

**Issue by thunder-coding** [termux/termux-packages#10854]
# How the transition should be done

> Note: this section should be considered incomplete. I'll appreciate some changes suggested by people who have maintained Qt family in the past.

- [ ] Add Qt6 family of packages
- [ ] Initial migration of a few packages to link against Qt6
- [ ] Manual testing of the packages now linked against Qt6
- [ ] Complete transition to Qt6 for all packages that successfully link against it.
- [ ] Deprecate Qt5 family of packages, and finally remove it later

**Comment by xtkoba** [comment]
Just some remarks.

Qt 5.15.x is planned to reach EOL at <a href="https://www.qt.io/blog/qt-5.15-extended-support-for-subscription-license-holders">26th May 2023</a>.

Qt 4.8.x reached EOL around <a href="https://www.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year">19th December 2015</a>. On Gentoo (a GNU/Linux distribution), the last removal of Qt 4 components was taken place on <a href="https://bugs.gentoo.org/show_bug.cgi?id=631788">7th August 2018</a>, more than 2 years and a half after EOL. Obviously it is not at all easy to fulfill all the tasks.

**Comment by TomJo2000** [comment]
Marking the first 3 points as completed after the merger of
- #19464

Currently introduced `qt6-*` packages:
- `qt6-qtbase`
- `qt6-qtmultimedia`
- `qt6-qtshadertools`
- `qt6-qtsvg`

Packages currently using Qt6:
- `feathernotes`
- `featherpad`
- `mkvtoolnix`

**Comment by twaik** [comment]
Probably this issue should be updated. There are a lot qt6 packages and their dependencies now.
<details>

```
twaik@twaikpc:~/termux-packages$ termux apt-cache rdepends qt6-qtbase
apt-cache rdepends qt6-qtbase
qt6-qtbase
Reverse Depends:
  qt6-qtbase-cross-tools
  texworks
  texstudio
  tageditor
  shotcut
  quazip
  qtxdg-tools
  qtutilities
  qtermwidget
  qterminal
  qt6ct
  qt6-shadertools
  qt6-qtwayland
  qt6-qttools
  qt6-qtsvg
  qt6-qtmultimedia
  qt6-qtlanguageserver
  qt6-qtimageformats
  qt6-qtdeclarative
  qt6-qtcharts
  ansifilter
  qt6-qt5compat
  qbittorrent-nox
  qbittorrent
  poppler-qt
  pcmanfm-qt
  pavucontrol-qt
  mogan
  mlt
  mkvtoolnix
  lxqt-session
  lxqt-runner
  lxqt-qtplugin
  lxqt-panel
  lxqt-openssh-askpass
  lxqt-notificationd
  lxqt-globalkeys
  lxqt-config
  lxqt-archiver
  lxqt-about
  lximage-qt
  libsysstat
  libqtxdg
  liblxqt
  libfm-qt
  libdbusmenu-lxqt
  layer-shell-qt
  kvantum
  kid3
  kf6-kwindowsystem
  kf6-kwidgetsaddons
  kf6-kitemviews
  kf6-kitemmodels
  kf6-ki18n
  kf6-kguiaddons
  kf6-kcoreaddons
  kf6-kconfig
  kf6-kcodecs
  kf6-kauth
  kf6-karchive
  heimer
  flacon
  featherpad
  feathernotes
  fcitx5-qt
  fcitx5-configtool
  audacious-plugins
  audacious
```
</details>

**Comment by TomJo2000** [comment]
> Probably this issue should be updated. There are a lot qt6 packages and their dependencies now.

Yep I hadn't kept up with that.
And with #21646 it's about to be a whole lot more.

**Comment by twaik** [comment]
`octave` package has an option of QT6 GUI, but it is not enabled. 
I tried to enable it, but it fails to be build (a lot of compiler errors).

**Comment by fornwall** [comment]
`nextcloud-client` (b3a6576a184b755d2164cd3196370741aee12de3) and `wireshark-qt` (0c3f58bdc134d7696c0cfab475ba253198fd220c) was just updated to Qt6 as well.

**Comment by fornwall** [comment]
Going through `apt rdepends qt5-qtbase`, filtering out already removed packages which are still present in the apt repo:

- Depends: qt5-qtbase-cross-tools
- Depends: qt5ct
- Depends: qt5-qtxmlpatterns
- Depends: qt5-qtx11extras
- Depends: qt5-qtwebsockets
- Depends: qt5-qtwebengine
- Depends: qt5-qtwebchannel
- Depends: qt5-qttools
- Depends: qt5-qtsvg
- Depends: qt5-qtserialport
- Depends: qt5-qtsensors
- Depends: qt5-qtscript
- Depends: qt5-qtmultimedia
- Depends: qt5-qtlocation
- Depends: qt5-qtdeclarative
- Depends: qt5-qtbase-gtk-platformtheme
- Depends: qt5-qtbase-cross-tools
- Depends: qt5-qmake
  - The above should all be supporting libraries, that can be removed once the below packages have been updated or retired
- Depends: qscintilla
  - Current versions seems to support Qt6
- Depends: qcustomplot
  - Only used by `polyphone`. Latest version should be Qt6 compatible
- Depends: polyphone
  - Latest version should be Qt6 compatible
- Depends: python-qscintilla
  - Should be able to transition to Qt6, once we have transitioned `qscintilla` and `pyqt5` -> `pyqt6`.
- Depends: python-pyqtwebengine
  - Should be able to transition to Qt6, once we have transitioned `pyqt5` -> `pyqt6` and have a `qt6-qtwebengine` package (which is a complex beast to build)
- Depends: pyqt5
  - pyqt6 exists.
- Depends: mumble-server
  - master branch switched to Qt6 on 2024-09-19 (https://github.com/mumble-voip/mumble/commit/de91daae08412aa55fa0052a89eb5af1f2858ba5), not yet released.
- Depends: mindforger
  - Issue, but no progress there yet: https://github.com/dvorka/mindforger/issues/1504
- Depends: lyx
  - Current version is Qt6 compatible
- Depends: vlc-qt
  - Qt6 support merged into master branch, scheduled for release in version 4: https://code.videolan.org/videolan/vlc/-/merge_requests/4783
- Depends: keepassxc
  - WIP PR: https://github.com/keepassxreboot/keepassxc/pull/10267
- Depends: fritzing
  - Latest version should be Qt6 compatible: #21875
- Depends: simulide
  - Cannot find any Qt6 progress - https://github.com/SimulIDE/SimulIDE
