### ISSUE TITLE
texlive: tracking future work

### ISSUE THREAD

**Issue by Grimler91** [termux/termux-packages#1456]
This issue is for tracking the work on various improving texlive for termux.

**To do list:**
- [x] Put files in standard locations (closed in https://github.com/termux/termux-packages/pull/2065)
- [ ] Develop script to move texmf-dist tree to external storage
- [x] Create pkg texlive-full and move tlmgr to it's own package
- [x] Handle tlpdb better
- [x] Specify packages instead of files
- [ ] Speed up tlmgr

<h2>Put files in standard locations</h2>

Install binaries in $PREFIX/bin and the texmf-dist to some appropriate location. We will need to redo the symlinks in termux_step_post_massage since the binaries and the texmf-dist scripts are no longer at the standard relative locations.

Care need to be taken when doing the change, the new version might brake the old version I guess. 

<h2>Develop script to move texmf-dist tree to external storage</h2>

Devices with limited internal storage would benefit from being able to move texlive's none-executable files to external storage. 

A guide on how to this can be written in the wiki.

<h2>Create pkg texlive-full and move tlmgr to it's own package</h2>

Create a full texlive package with all files not included in texlive or texlive-bin. 

texlive-full would depend on texlive and texlive-bin. They need different texlive.tlpdb files though and would hence conflict. To solve this, we can move tlmgr to it's own package and have it include the minimal texlive.tlpdb. 

texlive-full would then conflict with this package and include it's own, full, texlive.tlpdb. (texlive-full hence won't have tlmgr).

--------------------------
_copied from #1203:_
<h2>Handle tlpdb better</h2>

When the version of texlive is bumped, the upgrade replaces the texlive.tlpdb (the texlive database containing info about which packages has been installed) with the original (minimal) one. All tlmgr packages installed since the texlive package was first installed are then no longer recognized by tlmgr.

The files are still there and can be used but they cannot be upgraded through tlmgr.

Instead of overwriting the tlpdb on upgrade, it should be possible to merge the existing database with the one being installed. (The various scripts in texlive's dev sources at ftp://ftp.tug.org/texlive/historic/2017/texlive-20170524-devsource.tar.xz are probably useful for this).

<h2>Specify packages instead of files</h2>

Instead of having {texlive-texmf,texlive-extra,install-tl}.list, we should be able to just specify which packages we want and then extract which files these packages contains from texlive.tlpdb. This would make the build a bit nicer.

Again, I'm guessing the dev sources at ftp://ftp.tug.org/texlive/historic/2017/texlive-20170524-devsource.tar.xz would be useful for this.

<h2>Speed up tlmgr</h2>

tlmgr is quite slow at the moment, partly due to the option "--persistent-downloads" not working (due to some perl libs not being installed(?)).

**Comment by sdrausty** [comment]
Thank you for your awe inspiring work with tex and similar ☺

**Comment by sdrausty** [comment]
@Auxilus you have a very interesting proposal https://github.com/termux/termux-packages/pull/1514 Have you read the lastest at https://wiki.termux.com/wiki/Texlive#Package_Management about finding and selecting texlive packages? Do we want to spend the time and resources installing everything only to reinstall again and again?

**Comment by Grimler91** [comment]
I haven't updated this in a long time.

Point 1 is done and point 3 is progressing.
Creating texlive-full is progressing, it currently looks like we'll have:
texlive
texlive-bin
texlive-bin-dev
texlive-doc
texlive-fonts
texlive-fonts-type1
texlive-full
texlive-latex-doc
texlive-latex-doc1
texlive-latex-doc2
texlive-source
texlive-tlmgr

This amount of packages is needed to not exceed the maximum .deb size on the 32 bit arches (which seems to be a bit above 500 mb, deb extraction fails for larger debs).
The packages are all built as subpackages of texlive. It would be more intuitive (and shorter SUBPKG_INCLUDE-lists) to have a texlive-full package with the other packages as subpackages, but this requires some build-package.sh changes.
We need a "TERMUX_SUBPKG_BUILDORDER" variable and add more control fields to the subpackages, I'm looking into this at branch https://github.com/Grimler91/termux-packages/tree/build-package-improvements.

Choosing the SUBPKG_ORDER wisely makes point 5 unnecessay as we then can minimize the SUBPKG_INCLUDE lists (texlive first cherry-picks its files, the other subpackages then chooses their corresponding folders and texlive-full takes the rest).

The testing is happening at https://github.com/Grimler91/termux-packages/tree/texlive-dev and built debs are available at http://grimler.se/files/dists/testing/texlive/ (github didn't allow the large deb sizes so I couldn't use repo at grimler91.github.io). Pub key for repo is available at [pgp.mit.edu](http://pgp.mit.edu/pks/lookup?op=vindex&search=0x5AAAC9E0A46BE53C).

**Comment by sdrausty** [comment]
Jag har just granskat https://www.tug.org/texlive/distro.html denna sida. Det verkar som att tldistro@tug.org kanske vill veta om Texlive i Termux.

I have just reviewed https://www.tug.org/texlive/distro.html this page. It seems that tldistro@tug.org might want to know about Texlive in Termux.

**Comment by sdrausty** [comment]
Jag har just granskat https://www.tug.org/texlive/distro.html denna sida. Det verkar som att tldistro@tug.org kanske vill veta om Texlive i Termux.

I have just reviewed https://www.tug.org/texlive/distro.html this page. It seems that tldistro@tug.org might want to know about Texlive in Termux.

```
[13:10 home ]$ pacman -S biber texlive-most
warning: biber-2.11-1 is up to date -- reinstalling
:: There are 12 members in group texlive-most:
:: Repository extra
   1) texlive-bibtexextra  2) texlive-core  3) texlive-fontsextra
   4) texlive-formatsextra  5) texlive-games  6) texlive-humanities
   7) texlive-latexextra  8) texlive-music  9) texlive-pictures  10) texlive-pstricks
   11) texlive-publishers  12) texlive-science

Enter a selection (default=all):
```

**Comment by sdrausty** [comment]
[rastreo](https://github.com/termux/termux-packages/issues?utf8=%E2%9C%93&q=is%3Aissue+biber)

What is holding this up @Grimler91 ? biber, tex and Termux?

**Comment by Grimler91** [comment]
I've now uploaded texlive-full, at the same time as we updated to texlive 2019. It is split up according to texlive's collections. 

I am closing this issue as I've clearly not updated it regularly.
