### ISSUE TITLE
[TRACKER] Packages failing to build with Go 1.20 (related to quic-go)

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#14915]
As of writing, the following packages fail to build with Go 1.20.

- [x] <a href="https://github.com/termux/termux-packages/actions/runs/4086558457">algernon</a>
- [x] <a href="https://github.com/termux/termux-packages/actions/runs/4086640178">caddy</a>
- [ ] <a href="https://github.com/termux/termux-packages/actions/runs/4087007265">cloudflared</a>
- [x] <a href="https://github.com/termux/termux-packages/actions/runs/4086560411">frp</a>
- [x] <a href="https://github.com/termux/termux-packages/actions/runs/4086571964">ipfs</a>
- [x] <a href="https://github.com/termux/termux-packages/actions/runs/4086612468">storj-uplink</a>
- [x] <a href="https://github.com/termux/termux-packages/actions/runs/4086737351">syncthing</a>
- [x] <a href="https://github.com/termux/termux-packages/actions/runs/4086737351">v2ray</a>

All of them are related to <a href="https://github.com/quic-go/quic-go">`quic-go`</a>.

You don't need to file individual bugs for these packages. Thanks.

CC: @johndebia2022 (ardent reporter of build failures)

[EDIT] `bettercap` removed from list (unrelated to quic-go)
