### ISSUE TITLE
[TRACKER] packaging: Clang 16 porting (C)

### ISSUE THREAD

**Issue by xtkoba** [termux/termux-packages#15852]
See also https://wiki.gentoo.org/wiki/Modern_C_porting.

In Clang/LLVM 16 the following errors are enabled by default:

```
-Werror=implicit-function-declaration
-Werror=implicit-int
-Werror=int-conversion
-Werror=incompatible-function-pointer-types
```

In our packaging scripts, `TERMUX_PKG_ENABLE_CLANG16_PORTING` variable is introduced (6938b7c4b4d0e9b297fb0153560358706fc57b60) to control whether to enable these errors when using NDK r25 (based on Clang 14), to discover possible build failures/breakages with Clang 16.

Note that `TERMUX_PKG_ENABLE_CLANG16_PORTING` *is enabled by default* (set to `true`), and it is very likely that simply trying to rebuild some package leads to build failure/breakage.

To avoid catastrophic breakges or unnoticed breakages, it is explicitly (in `build.sh` of each package) disabled for essential packages (3c88b5956171da75c9a26178e9a92c28c09fd04f) and auto-updating packages (10ada7e4d39bcb7d3ec14a16dbf4b61c62a6af3d), until for each package it is sure that build failure/breakage does not occur.

It is acceptable that `TERMUX_PKG_ENABLE_CLANG16_PORTING` is set to `false` for each package by maintainer's decision, if this change of behavior is unwanted. But it is highly recommended that build failures/breakages be fixed instead.

**Comment by xtkoba** [comment]
Maybe not in effect when using CMake (`termux_step_configure_cmake`) because IIRC CMake does not use target-prefixed wrapper but calls `/path/to/clang` directly. There may be other cases where the clang16-porting switch does not effect.

I believe it is working for Autotools and Meson, unless the build scripts in the source do something insane.

**Comment by buttaface** [comment]
This is only relevant for on-device packaging?

**Comment by xtkoba** [comment]
Only affects non-on-device building. Does *not* affect on-device building at all, unless I'm doing anything wrong.

**Comment by buttaface** [comment]
OK, I thought this is because on-device builds use clang 16 from now on. Instead, you are getting these packages ready for the next NDK upgrade that uses clang 16? Because the current NDK 25 uses clang 14.

**Comment by xtkoba** [comment]
Porting to (upcoming) NDK r26 is one of the purposes. Another is to improve on-device building because our `clang` package is now Clang 16.

**Comment by truboxl** [comment]
So manual bump until NDK r26?

**Comment by TomJo2000** [comment]
So does this effect every package written in C/C++ in the repos or do you have like a list of (potentially) effected packages?

**Comment by xtkoba** [comment]
The following packages have passed the test as of now.

#### main

- [X] apr
- [X] apr-util
- [X] apt
- [X] argp
- [X] aspell
- [X] at-spi2-core
- [X] attr
- [X] autoconf
- [X] automake
- [X] avahi
- [X] babl
- [X] bash
- [X] bc
- [X] binutils-libs
- [X] bison
- [X] brotli
- [X] c-ares
- [X] ca-certificates
- [X] chromaprint
- [X] cmake
- [X] coreutils
- [X] dash
- [X] dbus
- [X] dialog
- [X] diffutils
- [X] double-conversion
- [X] dpkg
- [X] dropbear
- [X] enchant
- [X] exiv2
- [X] ffmpeg
- [X] fftw
- [X] file
- [X] findutils
- [X] flex
- [X] fluidsynth
- [X] fontconfig
- [X] freetype
- [X] fribidi
- [X] fzf
- [X] game-music-emu
- [X] gawk
- [X] gdb
- [X] gdbm
- [X] gdk-pixbuf
- [X] gegl
- [X] gettext
- [X] gexiv2
- [X] gflags
- [X] ghostscript
- [X] giflib
- [X] git
- [X] glib
- [X] gnupg
- [X] gobject-introspection
- [X] gperf
- [X] gpgme
- [X] graphene
- [X] grep
- [X] gsl
- [X] gst-plugins-bad
- [X] gst-plugins-base
- [X] gst-plugins-good
- [X] gstreamer
- [X] gzip
- [X] harfbuzz
- [X] hunspell
- [X] hunspell-en-us
- [X] imagemagick
- [X] imath
- [X] imlib2
- [X] jbig2dec
- [X] json-c
- [X] json-glib
- [X] jsoncpp
- [X] krb5
- [X] ldns
- [X] leptonica
- [X] less
- [X] liba52
- [X] libandroid-execinfo
- [X] libandroid-glob
- [X] libandroid-posix-semaphore
- [X] libandroid-shmem
- [X] libandroid-spawn
- [X] libandroid-support
- [X] libandroid-sysv-semaphore
- [X] libandroid-wordexp
- [X] libao
- [X] libaom
- [X] libarchive
- [X] libass
- [X] libassuan
- [X] libbluray
- [X] libbsd
- [X] libbz2
- [X] libc++
- [X] libcaca
- [X] libcairo
- [X] libcairomm-1.0
- [X] libcap
- [X] libcap-ng
- [X] libconfig
- [X] libconfuse
- [X] libcrypt
- [X] libcurl
- [X] libdaemon
- [X] libdav1d
- [X] libdb
- [X] libde265
- [X] libdrm
- [X] libdvdnav
- [X] libdvdread
- [X] libebml
- [X] libedit
- [X] libelf
- [X] libev
- [X] libevent
- [X] libexif
- [X] libexpat
- [X] libffi
- [X] libflac
- [X] libfreexl
- [X] libgc
- [X] libgcrypt
- [X] libgd
- [X] libgee
- [X] libgeos
- [X] libgit2
- [X] libglibmm-2.4
- [X] libglvnd
- [X] libgmime
- [X] libgmp
- [X] libgnutls
- [X] libgpg-error
- [X] libgraphite
- [X] libgsf
- [X] libgxps
- [X] libheif
- [X] libhyphen
- [X] libice
- [X] libiconv
- [X] libicu
- [X] libidn
- [X] libidn2
- [X] libimagequant
- [X] libjansson
- [X] libjasper
- [X] libjpeg-turbo
- [X] libjxl
- [X] libksba
- [X] libllvm
- [X] liblua52
- [X] liblua53
- [X] liblua54
- [X] libluajit
- [X] liblz4
- [X] liblzma
- [X] liblzo
- [X] libmad
- [X] libmd
- [X] libmediainfo
- [X] libminizip
- [X] libmnl
- [X] libmp3lame
- [X] libmpdclient
- [X] libmpfr
- [X] libmypaint
- [X] libnettle
- [X] libnfs
- [X] libnghttp2
- [X] libnl
- [X] libnpth
- [X] libnspr
- [X] libnss
- [X] libogg
- [X] libopenblas
- [X] libopus
- [X] libpangomm-1.4
- [X] libpaper
- [X] libpcap
- [X] libpixman
- [X] libpng
- [X] libpopt
- [X] libprotobuf-c
- [X] libpsl
- [X] libqrencode
- [X] librav1e
- [X] libre2
- [X] libresolv-wrapper
- [X] librsvg
- [X] librttopo
- [X] libsamplerate
- [X] libseccomp
- [X] libsecret
- [X] libsigc++-2.0
- [X] libsigc++-3.0
- [X] libsixel
- [X] libsm
- [X] libsnappy
- [X] libsndfile
- [X] libsodium
- [X] libsoup
- [X] libsoup3
- [X] libsoxr
- [X] libspatialite
- [X] libspectre
- [X] libsqlite
- [X] libssh
- [X] libssh2
- [X] libt3config
- [X] libtalloc
- [X] libtasn1
- [X] libtbb
- [X] libtdb
- [X] libtheora
- [X] libtiff
- [X] libtirpc
- [X] libtool
- [X] libuchardet
- [X] libudfread
- [X] libunibilium
- [X] libunistring
- [X] libusb
- [X] libuv
- [X] libvidstab
- [X] libvips
- [X] libvorbis
- [X] libvpx
- [X] libwebp
- [X] libwebrtc-audio-processing
- [X] libx11
- [X] libx264
- [X] libx265
- [X] libxapian
- [X] libxau
- [X] libxcb
- [X] libxcursor
- [X] libxdmcp
- [X] libxext
- [X] libxfixes
- [X] libxft
- [X] libxi
- [X] libxml2
- [X] libxrandr
- [X] libxrender
- [X] libxshmfence
- [X] libxslt
- [X] libxss
- [X] libxt
- [X] libxtst
- [X] libxv
- [X] libxxf86vm
- [X] libyaml
- [X] libzen
- [X] libzimg
- [X] libzip
- [X] libzmq
- [X] lilv
- [X] littlecms
- [X] lv2
- [X] m4
- [X] make
- [X] man
- [X] mesa
- [X] miniupnpc
- [X] mpg123
- [X] ncurses
- [X] netcdf-c
- [X] ocl-icd
- [X] oniguruma
- [X] openal-soft
- [X] openexr
- [X] openjpeg
- [X] openssh
- [X] openssl
- [X] openssl-1.1
- [X] opusfile
- [X] p11-kit
- [X] pango
- [X] pcre
- [X] pcre2
- [X] pinentry
- [X] pkg-config
- [X] poppler
- [X] postgresql
- [X] procps
- [X] proj
- [X] psmisc
- [X] pulseaudio
- [X] pycairo
- [X] pygobject
- [X] python
- [X] python-numpy
- [X] readline
- [X] resolv-conf
- [X] rhash
- [X] ruby
- [X] sed
- [X] serd
- [X] sord
- [X] speexdsp
- [X] sratom
- [X] taglib
- [X] tar
- [X] tcl
- [X] teckit
- [X] termux-am
- [X] termux-am-socket
- [X] termux-auth
- [X] termux-exec
- [X] termux-keyring
- [X] termux-licenses
- [X] termux-tools
- [X] tidy
- [X] tmux
- [X] unbound
- [X] utf8proc
- [X] util-linux
- [X] wget
- [X] woff2
- [X] xvidcore
- [X] xxhash
- [X] yajl
- [X] zlib
- [X] zsh
- [X] zstd
- [X] zziplib

#### x11

- [X] abiword
- [X] appstream-glib
- [X] ayatana-ido
- [X] caja
- [X] clutter
- [X] clutter-gst
- [X] clutter-gtk
- [X] cogl
- [X] dbus-glib
- [X] dconf
- [X] desktop-file-utils
- [X] eog
- [X] evince
- [X] exo
- [X] file-roller
- [X] garcon
- [X] gcr
- [X] gcr4
- [X] ghex
- [X] glade
- [X] glu
- [X] gnome-desktop3
- [X] gnome-desktop4
- [X] goffice
- [X] gsettings-desktop-schemas
- [X] gspell
- [X] gtk2
- [X] gtk3
- [X] gtk4
- [X] gtkmm3
- [X] gtksourceview3
- [X] gtksourceview4
- [X] gucharmap
- [X] iso-codes
- [X] keybinder
- [X] komorebi
- [X] libadwaita
- [X] libatkmm-1.6
- [X] libayatana-appindicator
- [X] libdazzle
- [X] libdbusmenu
- [X] libepoxy
- [X] libfm-extra
- [X] libfontenc
- [X] libhandy
- [X] libhandy-0.0
- [X] libmatekbd
- [X] libnotify
- [X] libpciaccess
- [X] libpeas
- [X] libportal
- [X] libunique
- [X] libvte
- [X] libwnck
- [X] libxaw
- [X] libxcomposite
- [X] libxcvt
- [X] libxdamage
- [X] libxfce4ui
- [X] libxfce4util
- [X] libxfont2
- [X] libxinerama
- [X] libxkbcommon
- [X] libxkbfile
- [X] libxklavier
- [X] libxmu
- [X] libxpm
- [X] mate-desktop
- [X] mate-menus
- [X] mate-panel
- [X] menu-cache
- [X] sdl
- [X] sdl2
- [X] shared-mime-info
- [X] startup-notification
- [X] thunar
- [X] tigervnc
- [X] vala-panel-appmenu
- [X] xcb-util
- [X] xcb-util-cursor
- [X] xcb-util-image
- [X] xcb-util-keysyms
- [X] xcb-util-renderutil
- [X] xcb-util-wm
- [X] xcb-util-xrm
- [X] xfce4-panel
- [X] xfconf
- [X] xkeyboard-config
- [X] xorg-font-util
- [X] xorg-mkfontscale
- [X] xorg-server
- [X] xorg-server-xvfb
- [X] xorg-xkbcomp

**Comment by xtkoba** [comment]
This does not check the C++ portability and I'm not going to do that in this issue.
