### ISSUE TITLE
[TRACKER] Packages failing to build with Go 1.21 (related to quic-go)

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-packages#17603]
- [x] [btfs2](https://github.com/termux/termux-packages/actions/runs/5840116490/job/15839008261)(enabled `TERMUX_PKG_GO_USE_OLDER`).
- [x] [dnslookup](https://github.com/termux/termux-packages/actions/runs/5839970053/job/15838709904) (enabled `TERMUX_PKG_GO_USE_OLDER`).
- [x] [q-dns-client](https://github.com/termux/termux-packages/actions/runs/5839425075/job/15837591765)
- [x] [syncthing](https://github.com/termux/termux-packages/actions/runs/5839434251/job/15837613097) ( [upstream issue](https://github.com/syncthing/syncthing/issues/9034) )
- [x] [ipfs](https://github.com/termux/termux-packages/actions/runs/5839623619/job/15837989680) ( [upstream issue](https://github.com/ipfs/kubo/issues/10064) ) waiting for release.
- [x] [frp](https://github.com/termux/termux-packages/actions/runs/5840455929/job/15839725830)
- [x] [flyctl](https://github.com/termux/termux-packages/actions/runs/5840506393/job/15839822699) ( [upstream issue](https://github.com/superfly/flyctl/issues/2688) )
- [x] [sing-box](https://github.com/termux/termux-packages/actions/runs/5840556208/job/15839915106)  ( [upstream issue](https://github.com/SagerNet/sing-box/issues/774) ) waiting for `1.4.0` stable release.
- [x] [v2ray](https://github.com/termux/termux-packages/actions/runs/5840952198/job/15840692651) ( [upstream issue](https://github.com/v2fly/v2ray-core/issues/2644) ), waiting for release.
