### ISSUE TITLE
Support for 16 KB page size on Android 15+

### ISSUE THREAD

**Issue by JunkFood02** [termux/termux-packages#21688]
### Problem description

Termux app itself and most termux packages haven't support support 16 KB page size yet

### What steps will reproduce the bug?

Running Termux on `Google APIs Experimental 16k Page Size ARM 64 v8a System Image`
https://developer.android.com/guide/practices/page-sizes#16kb-emulator

Or verify the ELF sections of any .so libraries in the apk or executables in the packages with the script below:
https://developer.android.com/guide/practices/page-sizes#test

### System information

```shell
No applicable
```

**Comment by JunkFood02** [comment]
Note: I'm raising this issue simply because it hasn't been brought up yet. This doesn't necessarily mean it's a high priority or that it's currently impacting any end-users. We can use this thread to discuss the potential impact of this change and any plans moving forward

This issue on termux-app:
- https://github.com/termux/termux-app/issues/4185

**Comment by truboxl** [comment]
Just wait for #21628

**Comment by Biswa96** [comment]
Q. If Android is built with 16KB page size, does that mean **all** termux packages **must** be recompiled with 16 KB page support?

**Comment by JunkFood02** [comment]
> Q. If Android is built with 16KB page size, does that mean all termux packages must be recompiled with 16 KB page support?

Yes.

But considering the massive impact of this change and the amount of legacy code in the entire ecosystem, this process may take longer than the transition from 'Google Play requiring 64-bit' to the 'launch of the first arm64-only phone (Pixel 7)'

**Comment by truboxl** [comment]
Let's turn this into a tracking issue for revbump all packages after NDK r28c is live.

**Comment by JunkFood02** [comment]
https://source.android.com/docs/core/architecture/16kb-page-size/16kb-backcompat-option

might be helpful in verifying potential behavior changes

**Comment by agnostic-apollo** [comment]
Following is the list of bootstrap packages and dependencies that need to be rebuilt.

- [x] apt
- [x] bash
- [x] bzip2
- [x] ca-certificates
- [x] command-not-found
- [x] coreutils
- [x] curl
- [x] dash
- [x] debianutils
- [x] dialog
- [x] diffutils
- [x] docbook-xml
- [x] docbook-xsl
- [x] dos2unix
- [x] dpkg
- [x] ed
- [x] findutils
- [x] gawk
- [x] gdbm
- [x] gnupg
- [x] gpgv
- [x] grep
- [x] gzip
- [x] inetutils
- [x] less
- [x] libandroid-glob
- [x] libandroid-posix-semaphore
- [x] libandroid-selinux
- [x] libandroid-support
- [x] libassuan
- [x] libbz2
- [x] libc++
- [x] libcap-ng
- [x] libcrypt
- [x] libcurl
- [x] libdb
- [x] libevent
- [x] libexpat
- [x] libffi
- [x] libgcrypt
- [x] libgmp
- [x] libgnutls
- [x] libgpg-error
- [x] libiconv
- [x] libidn2
- [x] libksba
- [x] liblz4
- [x] liblzma
- [x] libmd
- [x] libmpfr
- [x] libnettle
- [x] libnghttp2
- [x] libnghttp3
- [x] libnpth
- [x] libsqlite
- [x] libssh2
- [x] libtirpc
- [x] libunbound
- [x] libunistring
- [x] libxml2
- [x] libxslt
- [x] lsof
- [x] nano
- [x] ncurses
- [x] net-tools
- [x] openssl
- [x] patch
- [x] pcre2
- [x] pinentry
- [x] procps
- [x] psmisc
- [x] python
- [x] readline
- [x] resolv-conf
- [x] sed
- [x] swig
- [x] tar
- [x] tcl
- [x] termux-am
- [x] termux-am-socket
- [x] termux-core
- [x] termux-exec
- [x] termux-keyring
- [x] termux-licenses
- [x] termux-tools
- [x] unzip
- [x] util-linux
- [x] xxhash
- [x] xz-utils
- [x] zlib
- [x] zstd

**Comment by agnostic-apollo** [comment]
So bootstrap compiled from branch at https://github.com/termux/termux-packages/pull/24647#issuecomment-2859812965 and commits added on top from #25606 works for 16KB. The termux app JNI native libraries were also compiled with 16KB support.

<img width="1344" height="2992" alt="Image" src="https://github.com/user-attachments/assets/74a3a40f-d878-4523-b359-bc2c9d08562c" />

**Comment by agnostic-apollo** [comment]
I have converted the list of bootstrap packages above into a checkbox list, feel free to check packages that get rebuilt. Added some packages that were built during bootstrap as package dependencies but not added to the zips, best to rebuild them too.

**Comment by agnostic-apollo** [comment]
I think for some packages that may use dependencies statically, their dependencies would need to be rebuilt before the package itself, like `termux-core` before `termux-exec`, since I assume object files `.o` in static library files `.a` are compiled with the `max-page-size` alignment.

**Comment by MohammedKHC** [comment]
Now that @fornwall has successfully rebuilt all the bootstrap packages, should this issue be closed?

Thanks for your time, @fornwall. You're always the first to adapt to changes on the Android, just like with termux-exec on the Play Store version.
Thanks again!

**Comment by jiradave** [comment]
@agnostic-apollo @fornwall Is issue fixed? This is most critical bug and can be break play store apps and remove from play store if not done timely.

**Comment by agnostic-apollo** [comment]
It will not affect any existing users, only devices with only 16KB support by default will get affected, which would be rare. Playstore issues do exist, but that's managed by fornwall through separate github org, not by us. All bootstrap packages have already been rebuilt, but all 2000+ packages would need to be rebuilt, which will take time.

**Comment by jiradave** [comment]
@fornwall Can you please help us estimated time on when it will be completed?

> It will not affect any existing users, only devices with only 16KB support by default will get affected, which would be rare. Playstore issues do exist, but that's managed by fornwall through separate github org, not by us. All bootstrap packages have already been rebuilt, but all 2000+ packages would need to be rebuilt, which will take time.

**Comment by fornwall** [comment]
Almost all packages have now been rebuilt after the update to NDK r28, and thus have support for 16 kb page sizes.

The remaining ones (around 1-2% or so, I think) are packages that has not been in a buildable state since the NDK 28 update. They are covered by other issues (such as the #23492 tracking issue, and other more specific ones), and will either be fixed or the packages retired if they are too old to build with a modern toolchain. So closing this issue 🥳!

Report any specific problem around 16 kb page sizes in new issues.
